---
sidebar: sidebar 
permalink: get-started/cache-intro.html 
keywords: how bluexp volume caching works, what is volume caching, bluexp 
summary: Durch Volume Caching wird ein persistentes, beschreibbares Volume an einem Remote-Standort bereitgestellt. BlueXP Volume-Caching beschleunigt den Zugriff auf Daten und erleichtert die Verlagerung von Datenverkehr von Volumes, auf die sehr viel zugegriffen wird. Cache Volumes sind ideal für leseintensive Workloads, insbesondere wenn Clients wiederholt auf dieselben Daten zugreifen müssen. 
---
= Weitere Informationen zum BlueXP Volume-Caching
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Volume Caching, eine Funktion der ONTAP 9 Software, ist eine Remote-Caching-Funktion, die die Dateiverteilung vereinfacht, WAN-Latenz reduziert, indem Ressourcen näher an den Orten Ihrer Benutzer und Computing-Ressourcen gebracht werden und die Kosten für die WAN-Bandbreite gesenkt werden. Durch Volume Caching wird ein persistentes, beschreibbares Volume an einem Remote-Standort bereitgestellt. BlueXP Volume-Caching beschleunigt den Zugriff auf Daten und erleichtert die Verlagerung von Datenverkehr von Volumes, auf die sehr viel zugegriffen wird. Cache Volumes sind ideal für leseintensive Workloads, insbesondere wenn Clients wiederholt auf dieselben Daten zugreifen müssen.

Mit BlueXP Volume-Caching verfügen Sie über Caching-Funktionen für die Cloud, insbesondere für Amazon FSX for NetApp ONTAP, Cloud Volumes ONTAP und On-Premises als Arbeitsumgebungen.

Der Service bietet darüber hinaus Zugriff von Remote-Standorten auf unternehmenseigene Datensätze. Wenn Sie „heiße“ Daten bereitstellen, auf die häufig von mehreren Controllern in einem Cluster zugegriffen werden muss, können Sie die Performance wichtiger Applikationen steigern. Und wenn Sie heiße Daten für Benutzer an diversen Standorten weltweit in ihrem lokalen Cache zwischenspeichern, erleichtern Sie ihnen die engere Zusammenarbeit. Denn sie haben nicht nur gleichzeitigen Zugriff auf zentrale Datensätze, sondern auch verkürzte Reaktionszeiten beim Zugriff auf die „heißen“ Daten.



== Was ist ein Cache?

Ein Cache ist ein temporärer Speicherort, der sich zwischen einem Host und der Datenquelle befindet. Ziel eines Cache ist es, häufig genutzte Teile von Quelldaten so zu speichern, dass diese schneller verarbeitet werden können, als dies durch Abrufen der Daten von der Quelle der Fall wäre. Caches sind besonders in leseintensiven Umgebungen von Vorteil, in denen mehr als ein Mal auf Daten zugegriffen wird und von mehreren Hosts gemeinsam genutzt wird. Ein Cache-System ist schneller als das System mit Datenquelle. Dies wird durch ein schnelleres Storage-System und die Nähe des Cache-Speicherplatzes zum Host erreicht.



== Vorteile von BlueXP Volume Caching

BlueXP Volume Caching bietet folgende Vorteile:

* Performance-Steigerung in einer Hybrid-Cloud-Infrastruktur
* Entfernung von Cloud-Silos durch Caching der Daten von einem Cloud-Provider zu einem anderen
* Niedrigere Storage-Kosten
* Standortübergreifende Zusammenarbeit
* Nutzung eines durch NetApp gemanagten Services in BlueXP
* Schnellere Anpassung an sich ändernde IT-Umgebungen
* In der Cloud gehostete Volume-Caching nach Bedarf oder Abonnement




== Was Sie mit BlueXP Volume Caching erreichen können

Mit dem BlueXP Volume Caching können Sie mehrere NetApp Technologien vollumfänglich nutzen, um folgende Ziele zu erreichen:

Mit dem BlueXP Volume Caching Service profitieren Sie von allen NetApp Technologien, um folgende Ziele zu erreichen:

* Daten von einem Cloud-Provider zu einem anderen zwischenspeichern
* Anzeigen und Bearbeiten einer Cache-Exportrichtlinie
* Größe eines vorhandenen Caches ändern
* Cache löschen




== Kosten

NetApp berechnet Ihnen keine Kosten für die Nutzung des BlueXP Volume-Caching-Service, Sie müssen jedoch Ihren Cloud-Provider nach geltenden Datenein- und ausgehenden Gebühren fragen.



== Lizenzierung

Für das BlueXP Volume Caching sind keine speziellen ONTAP Lizenzen erforderlich.



== Funktionsweise von BlueXP Volume Caching

Ein Cache-Volume ist ein dünn besiedeltes Volume, das von einem Quell-Volume unterstützt wird. Das Cache-Volume kann sich auf demselben Cluster wie oder auf einem anderen Cluster befinden als das des Quell-Volume.

Das Cache-Volume ermöglicht den Zugriff auf Daten im Quell-Volume, ohne dass sich alle Daten im Cache-Volume befinden müssen. Für ein effizientes Management des Datenspeichern auf dem Cache Volume werden nur die „heißen“ Daten beibehalten (Arbeits- oder kürzlich verwendete Daten).

Im BlueXP Volume Caching werden Leseanforderungen angezeigt, wenn das Cache-Volume die vom Client angeforderten Daten enthält. Andernfalls fordert der Volume Caching-Service die Daten vom Quell-Volume an und speichert die Daten, bevor er die Client-Anfragen bedient. Nachfolgende Anfragen nach Daten werden direkt aus dem Cache Volume bedient. Dies verbessert die Leistung, wenn wiederholt auf dieselben Daten zugegriffen wird, da die Daten nach der ersten Anfrage nicht mehr über das Netzwerk reisen oder von einem überlasteten System bedient werden müssen.
